version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
artifacts:
- path: kalexi.Monads.Either\bin\Release\*.nupkg
  name: MyGet
deploy:
- provider: NuGet
  server: https://www.myget.org/F/kalexii/api/v2/package
  api_key:
    secure: SwcWTHMS4pVTjnMoLj2LJmq2hJZtffsE43XHIb/sRvOqzScWI4WeTZtjUFd4+B/9
  skip_symbols: true
  artifact: MyGet